CREATE TABLE [dbo].[Account]
(
	Id INT IDENTITY(1, 1) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	EmailConfirmed BIT NOT NULL DEFAULT 0,
	Username NVARCHAR(20) NOT NULL,
	UniqueId NVARCHAR(35) DEFAULT NULL,
	PasswordHash NVARCHAR(100) NOT NULL,
	PasswordSalt NVARCHAR(60) NOT NULL,
	AccessFailedCount INT NOT NULL DEFAULT 0,
	LockoutEnabled BIT NOT NULL DEFAULT 0,
	LockoutEnd DATETIME2(7) DEFAULT NULL,
	PhoneNumber NVARCHAR(20) DEFAULT NULL,
	PhoneNumberConfirmed BIT NOT NULL DEFAULT 0,
	TwoFactorEnabled BIT NOT NULL DEFAULT 0,
	TwoFaSecretKey NVARCHAR(12) DEFAULT NULL,
	CreatedOn DATETIME2(7) DEFAULT (GETDATE()),
	DeactivatedOn DATETIME2(7) DEFAULT NULL,
	RecoveryToken NVARCHAR(60) DEFAULT NULL,
	TokenSetOn DATETIME2(7) DEFAULT NULL,
	FcmToken NVARCHAR(100) DEFAULT NULL,
	CONSTRAINT [PK_Account_Id] PRIMARY KEY ([Id] ASC)
)
