CREATE TABLE [dbo].[Address]
(
	Id INT IDENTITY(1, 1) NOT NULL,
	[Name] NVARCHAR(50) DEFAULT NULL,
	Building NVARCHAR(30) DEFAULT NULL,
	Street NVARCHAR(50) DEFAULT NULL,
	Suburb NVARCHAR(30) DEFAULT NULL,
	Postcode NVARCHAR(10) DEFAULT NULL,
	[State] NVARCHAR(30) DEFAULT NULL,
	Country NVARCHAR(30) DEFAULT NULL,
	Latitude NVARCHAR(30) DEFAULT NULL,
	Longitude NVARCHAR(30) DEFAULT NULL,
	CONSTRAINT [PK_Address_Id] PRIMARY KEY ([Id] ASC)
)
