CREATE TABLE [dbo].[Address]
(
	Id INT IDENTITY(1, 1) NOT NULL,
	[Name] NVARCHAR(100) DEFAULT NULL,
	Building NVARCHAR(100) DEFAULT NULL,
	Street NVARCHAR(300) DEFAULT NULL,
	Suburb NVARCHAR(100) DEFAULT NULL,
	Postcode NVARCHAR(20) DEFAULT NULL,
	[State] NVARCHAR(100) DEFAULT NULL,
	Country NVARCHAR(100) DEFAULT NULL,
	Latitude NVARCHAR(30) DEFAULT NULL,
	Longitude NVARCHAR(30) DEFAULT NULL,
	CONSTRAINT [PK_Address_Id] PRIMARY KEY ([Id] ASC)
)
