CREATE TABLE [dbo].[AppSetting]
(
	Id INT IDENTITY(1, 1) NOT NULL,
	UserId INT NOT NULL,
	Theme TINYINT NOT NULL DEFAULT 3,
	IsPremium BIT NOT NULL DEFAULT 0,
	TodoUnlocked BIT NOT NULL DEFAULT 0,
	NoteUnlocked BIT NOT NULL DEFAULT 0,
	CollabUnlocked BIT NOT NULL DEFAULT 0,
	ShouldHideAds BIT NOT NULL DEFAULT 0,
	PremiumUntil DATETIME2(7) DEFAULT NULL,
	UnlockedUntil DATETIME2(7) DEFAULT NULL,
	DateTimeFormat NVARCHAR NOT NULL DEFAULT 'FRIENDLY_DMY',
	UnitSystem TINYINT NOT NULL DEFAULT 0,
	AddressFormat TINYINT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_AppSetting_Id] PRIMARY KEY ([Id] ASC),
	CONSTRAINT [FK_AppSetting_User_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id]) --ON DELETE CASCADE
)
