CREATE TABLE [dbo].[Note]
(
	Id INT IDENTITY(1, 1) NOT NULL,
	UserId INT NOT NULL,
	IsShared BIT NOT NULL DEFAULT 0,
	Emphasized BIT NOT NULL DEFAULT 0,
	Title NVARCHAR(100) DEFAULT NULL,
	CreatedOn DATETIME2(7) NOT NULL DEFAULT (GETDATE()),
	DeletedOn NVARCHAR(7) DEFAULT NULL,
	CONSTRAINT [PK_Note_Id] PRIMARY KEY ([Id] ASC),
	CONSTRAINT [FK_Note_User_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id]) --ON DELETE CASCADE
)
