CREATE TABLE [dbo].[UserRsaKey]
(
	Id INT IDENTITY(1, 1) NOT NULL,
	UserId INT NOT NULL,
	SignatureEnabled BIT NOT NULL DEFAULT 0,
	KeyModulus NVARCHAR(250) NOT NULL,
	KeyExponent NVARCHAR(50) NOT NULL,
	PublicKey NVARCHAR(4000) NOT NULL,
	PrivateKey NVARCHAR(4000) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 0,
	GeneratedOn DATETIME2(7) NOT NULL DEFAULT (GETDATE()),
	CONSTRAINT [PK_UserRsaKey_Id] PRIMARY KEY ([Id] ASC),
	CONSTRAINT [FK_UserRsaKey_User_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id]) --ON DELETE CASCADE
)
